In [1]:
# Import the required libraries
import pandas as pd
from google.colab import files

# Upload the dataset from your computer
uploaded = files.upload()

# Get the uploaded filename automatically
file_name = next(iter(uploaded))

# Load the CSV file into a pandas DataFrame
df = pd.read_csv(file_name, low_memory=False)

# Confirm that the dataset was loaded
print("\nDataset loaded successfully!")
print(f"File name: {file_name}")
print(f"Number of rows: {df.shape[0]:,}")
print(f"Number of columns: {df.shape[1]}")

# Display the first five rows
print("\nFirst five rows:")
display(df.head())

# Display all column names
print("\nColumn names:")
print(df.columns.tolist())

# Display column data types and non-null counts
print("\nDataset information:")
df.info()

# Check missing values
print("\nMissing values in each column:")
missing_values = df.isnull().sum().sort_values(ascending=False)
display(missing_values.to_frame(name="Missing Values"))

# Check completely duplicated rows
duplicate_count = df.duplicated().sum()
print(f"\nNumber of duplicate rows: {duplicate_count:,}")

Saving AcmeRetail_Products_70000.csv to AcmeRetail_Products_70000.csv

Dataset loaded successfully!
File name: AcmeRetail_Products_70000.csv
Number of rows: 70,000
Number of columns: 10

First five rows:

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,8994,MyBlush Women Top,women's clothing,Western Wear,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/MyBlush-Womens-Solid-Cla...,3.5,9,₹699,"₹2,299"
1,6994,Ridhi Home & Decor Brass Decorative Weighing S...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Brass-Decorative-Weighin...,3.7,64,₹380,₹500
2,7494,Rangshaily Men's Black White Floral Print Full...,men's clothing,Shirts,https://m.media-amazon.com/images/I/51oiWRu+Gp...,https://www.amazon.in/Rangshaily-Regular-Flora...,NaN,NaN,₹649,₹999
3,5066,Adidas Men's Ellipto Run M Leather Shoe,men's shoes,Sports Shoes,https://m.media-amazon.com/images/I/71RsZ19e-w...,https://www.amazon.in/Adidas-Ellipto-Running-D...,3.6,23,"₹1,274","₹2,499"
4,14687,JJ TEES Polyester Half Sleeve Jersey with Roun...,men's clothing,T-shirts & Polos,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/JJ-TEES-Polyester-Sleeve...,3.5,10,₹345,₹999

Column names:
['Unnamed: 0', 'name', 'main_category', 'sub_category', 'image', 'link', 'ratings', 'no_of_ratings', 'discount_price', 'actual_price']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      70000 non-null  int64
 1   name            70000 non-null  object
 2   main_category   70000 non-null  object
 3   sub_category    70000 non-null  object
 4   image           70000 non-null  object
 5   link            70000 non-null  object
 6   ratings         47650 non-null  object
 7   no_of_ratings   47650 non-null  object
 8   discount_price  62177 non-null  object
 9   actual_price    67711 non-null  object
dtypes: int64(1), object(9)
memory usage: 5.3+ MB

Missing values in each column:

                Missing Values
ratings                  22350
no_of_ratings            22350
discount_price            7823
actual_price              2289
name                         0
Unnamed: 0                   0
link                         0
image                        0
sub_category                 0
main_category                0

Number of duplicate rows: 0

In [2]:
# Part 2: Data Understanding

# Check the number of rows and columns
print("Dataset shape:", df.shape)

# Display the first five rows
print("\nFirst five rows:")
display(df.head())

# Display column names
print("\nColumn names:")
print(df.columns.tolist())

# Check column data types and non-null values
print("\nDataset information:")
df.info()

# Check missing values
print("\nMissing values:")
print(df.isnull().sum())

# Check duplicate rows
print("\nDuplicate rows:", df.duplicated().sum())

# Display basic statistics
print("\nBasic statistics:")
display(df.describe(include="all"))

Dataset shape: (70000, 10)

First five rows:

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,8994,MyBlush Women Top,women's clothing,Western Wear,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/MyBlush-Womens-Solid-Cla...,3.5,9,₹699,"₹2,299"
1,6994,Ridhi Home & Decor Brass Decorative Weighing S...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Brass-Decorative-Weighin...,3.7,64,₹380,₹500
2,7494,Rangshaily Men's Black White Floral Print Full...,men's clothing,Shirts,https://m.media-amazon.com/images/I/51oiWRu+Gp...,https://www.amazon.in/Rangshaily-Regular-Flora...,NaN,NaN,₹649,₹999
3,5066,Adidas Men's Ellipto Run M Leather Shoe,men's shoes,Sports Shoes,https://m.media-amazon.com/images/I/71RsZ19e-w...,https://www.amazon.in/Adidas-Ellipto-Running-D...,3.6,23,"₹1,274","₹2,499"
4,14687,JJ TEES Polyester Half Sleeve Jersey with Roun...,men's clothing,T-shirts & Polos,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/JJ-TEES-Polyester-Sleeve...,3.5,10,₹345,₹999

Column names:
['Unnamed: 0', 'name', 'main_category', 'sub_category', 'image', 'link', 'ratings', 'no_of_ratings', 'discount_price', 'actual_price']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      70000 non-null  int64
 1   name            70000 non-null  object
 2   main_category   70000 non-null  object
 3   sub_category    70000 non-null  object
 4   image           70000 non-null  object
 5   link            70000 non-null  object
 6   ratings         47650 non-null  object
 7   no_of_ratings   47650 non-null  object
 8   discount_price  62177 non-null  object
 9   actual_price    67711 non-null  object
dtypes: int64(1), object(9)
memory usage: 5.3+ MB

Missing values:
Unnamed: 0            0
name                  0
main_category         0
sub_category          0
image                 0
link                  0
ratings           22350
no_of_ratings     22350
discount_price     7823
actual_price       2289
dtype: int64

Duplicate rows: 0

Basic statistics:

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
count,70000.000000,70000,70000,70000,70000,70000,47650,47650,62177,67711
unique,NaN,63333,20,112,66793,70000,44,3546,8117,6851
top,NaN,Zeya Yellow Gold Ring,accessories,Jeans,https://m.media-amazon.com/images/I/51uEPldT42...,https://www.amazon.in/Natural-Care-Car-Exterio...,4,1,₹499,₹999
freq,NaN,80,14615,2538,395,1,4615,5041,2283,6121
mean,6997.041829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,5739.439738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1548.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,5913.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,11468.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,19199.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Part 3: Data Preparation

# Create a copy of the original dataset
data = df.copy()

# Remove the unnecessary index column
data.drop(columns=["Unnamed: 0"], errors="ignore", inplace=True)

# Remove duplicate rows
data.drop_duplicates(inplace=True)

# Remove records where the product name is missing
data.dropna(subset=["name"], inplace=True)

# Fill missing category values
data["main_category"] = data["main_category"].fillna("unknown")
data["sub_category"] = data["sub_category"].fillna("unknown")

# Clean the text columns
text_columns = ["name", "main_category", "sub_category"]

for column in text_columns:
    data[column] = data[column].astype(str).str.lower().str.strip()

# Convert rating columns into numbers
data["ratings"] = pd.to_numeric(data["ratings"], errors="coerce")

data["no_of_ratings"] = pd.to_numeric(
    data["no_of_ratings"].astype(str).str.replace(",", "", regex=False),
    errors="coerce"
)

# Remove currency symbols and commas from price columns
price_columns = ["discount_price", "actual_price"]

for column in price_columns:
    data[column] = pd.to_numeric(
        data[column].astype(str).str.replace(r"[₹,]", "", regex=True),
        errors="coerce"
    )

# Create one text column for the NLP similarity model
data["combined_text"] = (
    data["name"] + " " +
    data["main_category"] + " " +
    data["sub_category"]
)

# Reset the row numbers
data.reset_index(drop=True, inplace=True)

# Display the prepared dataset
print("Data preparation completed.")
print("Dataset shape:", data.shape)
print("\nMissing values:")
print(data.isnull().sum())

display(data.head())

Data preparation completed.
Dataset shape: (70000, 10)

Missing values:
name                  0
main_category         0
sub_category          0
image                 0
link                  0
ratings           23183
no_of_ratings     23183
discount_price     7823
actual_price       2289
combined_text         0
dtype: int64

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price,combined_text
0,myblush women top,women's clothing,western wear,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/MyBlush-Womens-Solid-Cla...,3.5,9.0,699.0,2299.0,myblush women top women's clothing western wear
1,ridhi home & decor brass decorative weighing s...,appliances,all appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Brass-Decorative-Weighin...,3.7,64.0,380.0,500.0,ridhi home & decor brass decorative weighing s...
2,rangshaily men's black white floral print full...,men's clothing,shirts,https://m.media-amazon.com/images/I/51oiWRu+Gp...,https://www.amazon.in/Rangshaily-Regular-Flora...,NaN,NaN,649.0,999.0,rangshaily men's black white floral print full...
3,adidas men's ellipto run m leather shoe,men's shoes,sports shoes,https://m.media-amazon.com/images/I/71RsZ19e-w...,https://www.amazon.in/Adidas-Ellipto-Running-D...,3.6,23.0,1274.0,2499.0,adidas men's ellipto run m leather shoe men's ...
4,jj tees polyester half sleeve jersey with roun...,men's clothing,t-shirts & polos,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/JJ-TEES-Polyester-Sleeve...,3.5,10.0,345.0,999.0,jj tees polyester half sleeve jersey with roun...

In [4]:
# Part 4: Text Preprocessing

import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download the required NLTK resources
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

# Create the stop-word list and lemmatizer
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

# Function to clean product text
def preprocess_text(text):
    # Convert text to lowercase
    text = str(text).lower()

    # Remove punctuation, numbers and special characters
    text = re.sub(r"[^a-z\s]", " ", text)

    # Split the sentence into individual words
    words = text.split()

    # Remove stop words and convert words to their base forms
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    # Join the words back into a sentence
    return " ".join(words)

# Apply preprocessing to the combined product text
data["clean_text"] = data["combined_text"].apply(preprocess_text)

# Remove rows that contain no usable text
data = data[data["clean_text"].str.strip() != ""]

# Reset row numbers
data.reset_index(drop=True, inplace=True)

# Compare the original and cleaned text
print("Text preprocessing completed.")
display(data[["combined_text", "clean_text"]].head(10))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

Text preprocessing completed.

,combined_text,clean_text
0,myblush women top women's clothing western wear,myblush woman top woman clothing western wear
1,ridhi home & decor brass decorative weighing s...,ridhi home decor brass decorative weighing sca...
2,rangshaily men's black white floral print full...,rangshaily men black white floral print fullsl...
3,adidas men's ellipto run m leather shoe men's ...,adidas men ellipto run leather shoe men shoe s...
4,jj tees polyester half sleeve jersey with roun...,jj tee polyester half sleeve jersey round coll...
5,aones pack of 3 magnetic loop watch strap comp...,aones pack magnetic loop watch strap compatibl...
6,avsar 14k (585) yellow gold ring for women acc...,avsar k yellow gold ring woman accessory gold ...
7,jockey modern trunks with double layer contour...,jockey modern trunk double layer contoured pou...
8,nilus cute and shiny stone chain bracelet for ...,nilus cute shiny stone chain bracelet woman gi...
9,chappal mens leather handmade formal shoes - b...,chappal men leather handmade formal shoe brown...

In [5]:
# Part 5: TF-IDF Model and Cosine Similarity Search System

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ------------------------------------------
# 1. Build the TF-IDF model
# ------------------------------------------

tfidf_model = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2),
    min_df=2
)

# Train the model and transform the cleaned text
tfidf_matrix = tfidf_model.fit_transform(data["clean_text"])

print("TF-IDF model built successfully.")
print("TF-IDF matrix shape:", tfidf_matrix.shape)


# ------------------------------------------
# 2. Create the recommendation function
# ------------------------------------------

def recommend_products(product_name, number_of_recommendations=5):

    # Search for the product name
    matching_products = data[
        data["name"].str.contains(
            product_name,
            case=False,
            na=False,
            regex=False
        )
    ]

    # Check whether the product exists
    if matching_products.empty:
        print("Product not found. Please try another product name.")
        return

    # Select the first matching product
    product_index = matching_products.index[0]
    selected_product = data.loc[product_index, "name"]

    print(f"\nSelected product: {selected_product}")

    # Calculate similarity with all other products
    similarity_scores = cosine_similarity(
        tfidf_matrix[product_index],
        tfidf_matrix
    ).flatten()

    # Sort products from most similar to least similar
    similar_indices = similarity_scores.argsort()[::-1]

    # Remove the selected product itself
    similar_indices = [
        index for index in similar_indices
        if index != product_index
    ]

    # Keep only the requested number of recommendations
    similar_indices = similar_indices[:number_of_recommendations]

    # Select useful result columns
    result_columns = [
        "name",
        "main_category",
        "sub_category",
        "ratings",
        "discount_price"
    ]

    recommendations = data.loc[
        similar_indices,
        result_columns
    ].copy()

    # Add similarity scores
    recommendations["similarity_score"] = similarity_scores[
        similar_indices
    ]

    # Reset row numbers
    recommendations.reset_index(drop=True, inplace=True)
    recommendations.index = recommendations.index + 1

    return recommendations


# ------------------------------------------
# 3. Test the recommendation system
# ------------------------------------------

search_product = input("\nEnter a product name: ")

results = recommend_products(
    search_product,
    number_of_recommendations=5
)

if results is not None:
    display(results)

TF-IDF model built successfully.
TF-IDF matrix shape: (70000, 20000)

Enter a product name: women top

Selected product: myblush women top

,name,main_category,sub_category,ratings,discount_price,similarity_score
1,misverse women top,women's clothing,western wear,3.1,699.0,1.0
2,lyriq women tops,women's clothing,western wear,4.7,399.0,1.0
3,clothzy women's top,women's clothing,western wear,3.7,319.0,1.0
4,midaas women's top,women's clothing,western wear,3.8,209.0,1.0
5,mizago women's top,women's clothing,western wear,3.4,599.0,1.0

In [6]:
# Part 6: Word2Vec Model and Cosine Similarity Search System

!pip install -q gensim

import numpy as np

from gensim.models import Word2Vec
from sklearn.metrics.pairwise import cosine_similarity

# ------------------------------------------
# 1. Convert cleaned text into word lists
# ------------------------------------------

sentences = data["clean_text"].apply(lambda text: text.split()).tolist()

# ------------------------------------------
# 2. Train the Word2Vec model
# ------------------------------------------

word2vec_model = Word2Vec(
    sentences=sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    epochs=10,
    seed=42
)

print("Word2Vec model trained successfully.")
print("Vocabulary size:", len(word2vec_model.wv))

# ------------------------------------------
# 3. Create one vector for each product
# ------------------------------------------

def create_product_vector(text):
    words = text.split()

    # Keep only words learned by Word2Vec
    word_vectors = [
        word2vec_model.wv[word]
        for word in words
        if word in word2vec_model.wv
    ]

    # Return the average word vector
    if word_vectors:
        return np.mean(word_vectors, axis=0)

    # Return a zero vector if no words were found
    return np.zeros(word2vec_model.vector_size)


product_vectors = np.array(
    data["clean_text"].apply(create_product_vector).tolist()
)

print("Product-vector matrix shape:", product_vectors.shape)

# ------------------------------------------
# 4. Create the recommendation function
# ------------------------------------------

def recommend_products_word2vec(product_name, number_of_recommendations=5):

    # Find products containing the search text
    matching_products = data[
        data["name"].str.contains(
            product_name,
            case=False,
            na=False,
            regex=False
        )
    ]

    if matching_products.empty:
        print("Product not found. Please try another product name.")
        return

    # Select the first matching product
    product_index = matching_products.index[0]
    selected_product = data.loc[product_index, "name"]

    print(f"\nSelected product: {selected_product}")

    # Calculate cosine similarity
    similarity_scores = cosine_similarity(
        product_vectors[product_index].reshape(1, -1),
        product_vectors
    ).flatten()

    # Sort products by similarity
    similar_indices = similarity_scores.argsort()[::-1]

    # Exclude the selected product
    similar_indices = [
        index for index in similar_indices
        if index != product_index
    ][:number_of_recommendations]

    # Prepare the results
    result_columns = [
        "name",
        "main_category",
        "sub_category",
        "ratings",
        "discount_price"
    ]

    recommendations = data.loc[
        similar_indices,
        result_columns
    ].copy()

    recommendations["similarity_score"] = similarity_scores[
        similar_indices
    ]

    recommendations.reset_index(drop=True, inplace=True)
    recommendations.index = recommendations.index + 1

    return recommendations

# ------------------------------------------
# 5. Test the recommendation system
# ------------------------------------------

search_product = input("\nEnter a product name: ")

results = recommend_products_word2vec(
    search_product,
    number_of_recommendations=5
)

if results is not None:
    display(results)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 60.3 MB/s eta 0:00:00
Word2Vec model trained successfully.
Vocabulary size: 19201
Product-vector matrix shape: (70000, 100)

Enter a product name: women top

Selected product: myblush women top

,name,main_category,sub_category,ratings,discount_price,similarity_score
1,mizago women's top,women's clothing,western wear,3.4,599.0,0.999988
2,clothzy women's top,women's clothing,western wear,3.7,319.0,0.999985
3,prettify women's top,women's clothing,western wear,5.0,799.0,0.999985
4,siddhanam women top,women's clothing,western wear,3.6,NaN,0.999982
5,misverse women top,women's clothing,western wear,3.1,699.0,0.999973

In [7]:
# Part 7: FastText Model and Cosine Similarity Search System

!pip install -q gensim

import numpy as np

from gensim.models import FastText
from sklearn.metrics.pairwise import cosine_similarity

# ------------------------------------------
# 1. Convert cleaned text into word lists
# ------------------------------------------

sentences = data["clean_text"].apply(lambda text: text.split()).tolist()

# ------------------------------------------
# 2. Train the FastText model
# ------------------------------------------

fasttext_model = FastText(
    sentences=sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    epochs=10,
    seed=42
)

print("FastText model trained successfully.")
print("Vocabulary size:", len(fasttext_model.wv))

# ------------------------------------------
# 3. Create one vector for each product
# ------------------------------------------

def create_fasttext_vector(text):
    words = text.split()

    if len(words) == 0:
        return np.zeros(fasttext_model.vector_size)

    word_vectors = [
        fasttext_model.wv[word]
        for word in words
    ]

    return np.mean(word_vectors, axis=0)


fasttext_product_vectors = np.array(
    data["clean_text"].apply(create_fasttext_vector).tolist()
)

print(
    "Product-vector matrix shape:",
    fasttext_product_vectors.shape
)

# ------------------------------------------
# 4. Create the recommendation function
# ------------------------------------------

def recommend_products_fasttext(
    product_name,
    number_of_recommendations=5
):

    # Find products containing the entered text
    matching_products = data[
        data["name"].str.contains(
            product_name,
            case=False,
            na=False,
            regex=False
        )
    ]

    if matching_products.empty:
        print("Product not found. Please try another product name.")
        return

    # Select the first matching product
    product_index = matching_products.index[0]
    selected_product = data.loc[product_index, "name"]

    print(f"\nSelected product: {selected_product}")

    # Calculate cosine similarity
    similarity_scores = cosine_similarity(
        fasttext_product_vectors[product_index].reshape(1, -1),
        fasttext_product_vectors
    ).flatten()

    # Sort products from most similar to least similar
    similar_indices = similarity_scores.argsort()[::-1]

    # Remove the selected product
    similar_indices = [
        index for index in similar_indices
        if index != product_index
    ][:number_of_recommendations]

    # Prepare recommendation results
    result_columns = [
        "name",
        "main_category",
        "sub_category",
        "ratings",
        "discount_price"
    ]

    recommendations = data.loc[
        similar_indices,
        result_columns
    ].copy()

    # Add similarity scores
    recommendations["similarity_score"] = similarity_scores[
        similar_indices
    ]

    # Reset the displayed row numbers
    recommendations.reset_index(drop=True, inplace=True)
    recommendations.index = recommendations.index + 1

    return recommendations

# ------------------------------------------
# 5. Test the recommendation system
# ------------------------------------------

search_product = input("\nEnter a product name: ")

results = recommend_products_fasttext(
    search_product,
    number_of_recommendations=5
)

if results is not None:
    display(results)

FastText model trained successfully.
Vocabulary size: 19201
Product-vector matrix shape: (70000, 100)

Enter a product name: women top

Selected product: myblush women top

,name,main_category,sub_category,ratings,discount_price,similarity_score
1,women ponchos top,women's clothing,western wear,4.3,799.0,0.998801
2,misverse women top,women's clothing,western wear,3.1,699.0,0.998733
3,prettify women's top,women's clothing,western wear,5.0,799.0,0.998730
4,mizago women's top,women's clothing,western wear,3.4,599.0,0.998729
5,lyriq women tops,women's clothing,western wear,4.7,399.0,0.998601

In [10]:

# Part 8: Compare TF-IDF, Word2Vec and FastText Models

import time
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# Number of recommendations
k = 5

# Select 50 random products for evaluation
sample_indices = data.sample(
    n=min(50, len(data)),
    random_state=42
).index


# Function to find the top similar products
def get_similar_products(product_index, vectors, k=5):

    # Get the selected product vector
    selected_vector = vectors[product_index]

    # Word2Vec and FastText return a 1D vector.
    # Convert it into a 2D vector for cosine similarity.
    if selected_vector.ndim == 1:
        selected_vector = selected_vector.reshape(1, -1)

    # Calculate similarity scores
    similarity_scores = cosine_similarity(
        selected_vector,
        vectors
    ).flatten()

    # Exclude the selected product itself
    similarity_scores[product_index] = -1

    # Get the top similar products
    similar_indices = similarity_scores.argsort()[::-1][:k]

    return similar_indices


# Function to evaluate one model
def evaluate_model(model_name, vectors):

    main_category_scores = []
    sub_category_scores = []
    execution_times = []

    for product_index in sample_indices:

        start_time = time.time()

        similar_indices = get_similar_products(
            product_index,
            vectors,
            k
        )

        execution_times.append(time.time() - start_time)

        original_main_category = data.loc[
            product_index, "main_category"
        ]

        original_sub_category = data.loc[
            product_index, "sub_category"
        ]

        recommended_main_categories = data.loc[
            similar_indices, "main_category"
        ]

        recommended_sub_categories = data.loc[
            similar_indices, "sub_category"
        ]

        # Calculate Precision@5
        main_precision = (
            recommended_main_categories == original_main_category
        ).mean()

        sub_precision = (
            recommended_sub_categories == original_sub_category
        ).mean()

        main_category_scores.append(main_precision)
        sub_category_scores.append(sub_precision)

    return {
        "Model": model_name,
        "Main Category Precision@5": np.mean(main_category_scores),
        "Subcategory Precision@5": np.mean(sub_category_scores),
        "Average Search Time": np.mean(execution_times)
    }


# Evaluate all three models
tfidf_result = evaluate_model(
    "TF-IDF",
    tfidf_matrix
)

word2vec_result = evaluate_model(
    "Word2Vec",
    product_vectors
)

fasttext_result = evaluate_model(
    "FastText",
    fasttext_product_vectors
)

# Create the comparison table
comparison = pd.DataFrame([
    tfidf_result,
    word2vec_result,
    fasttext_result
])

# Format the results
comparison["Main Category Precision@5"] = (
    comparison["Main Category Precision@5"].round(3)
)

comparison["Subcategory Precision@5"] = (
    comparison["Subcategory Precision@5"].round(3)
)

comparison["Average Search Time"] = (
    comparison["Average Search Time"].round(4)
)

# Display results
print("Model Evaluation Results:")
display(comparison)

# Display the best model
best_model = comparison.loc[
    comparison["Subcategory Precision@5"].idxmax(),
    "Model"
]

print("Best model based on Subcategory Precision@5:", best_model)

Model Evaluation Results:

,Model,Main Category Precision@5,Subcategory Precision@5,Average Search Time
0,TF-IDF,0.960,0.840,0.0887
1,Word2Vec,0.948,0.864,0.0658
2,FastText,0.936,0.800,0.0348

Best model based on Subcategory Precision@5: Word2Vec

In [11]:
# Export FastText model files from Google Colab

import os
import shutil
import numpy as np
from google.colab import files

# Create a folder for exported files
export_folder = "/content/fasttext_artifacts"
os.makedirs(export_folder, exist_ok=True)

# 1. Save the prepared product dataset
data.to_csv(
    f"{export_folder}/prepared_products.csv",
    index=False
)

# 2. Save the trained FastText model
fasttext_model.save(
    f"{export_folder}/fasttext.model"
)

# 3. Save all product vectors
np.save(
    f"{export_folder}/fasttext_product_vectors.npy",
    fasttext_product_vectors
)

# 4. Copy the original dataset into the same folder
original_csv = "/content/AcmeRetail_Products_70000.csv"

if os.path.exists(original_csv):
    shutil.copy(
        original_csv,
        f"{export_folder}/AcmeRetail_Products_70000.csv"
    )
else:
    print("Original CSV was not found, but the other files were saved.")

# 5. Display the exported files
print("\nExported files:")

for file_name in os.listdir(export_folder):
    file_size = os.path.getsize(
        os.path.join(export_folder, file_name)
    ) / (1024 * 1024)

    print(f"{file_name}: {file_size:.2f} MB")

# 6. Create one ZIP file
zip_path = shutil.make_archive(
    "/content/fasttext_artifacts",
    "zip",
    export_folder
)

print("\nFiles exported successfully.")

# 7. Download the ZIP file
files.download(zip_path)

Exported files:
fasttext.model: 15.19 MB
AcmeRetail_Products_70000.csv: 22.80 MB
fasttext_product_vectors.npy: 26.70 MB
fasttext.model.wv.vectors_ngrams.npy: 762.94 MB
prepared_products.csv: 35.78 MB

Files exported successfully.